name: test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: env
        env:
          NODE_ENV: ${{secrets.NODE_ENV}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
